# Generated by Django 4.2 on 2023-04-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_nickcname',
            new_name='user_nickname',
        ),
    ]
